data:extend({
  {
    type = "int-setting",
    name = "Construction-robots-count",
    order = "aa",
    setting_type = "startup",
    default_value = 100,
  },
  {
	type = "int-setting",
	name = "Repair-tool-count",
	order = "aba",
	setting_type = "startup",
	default_value = 100,
  },
  {
	type = "string-setting",
	name = "Repair-tool-type",
	order = "abb",
	setting_type = "startup",
	default_value = "titanium-repair-tool",
	allowed_values = {"copper-repair-tool","bronze-repair-tool","iron-repair-tool","steel-repair-tool","titanium-repair-tool",},
  },
  {
	type = "bool-setting",
	name = "Use-steambots",
	order = "ac",
	setting_type = "startup",
	default_value = true,
  }, 
  {
    type = "int-setting",
    name = "Uranium-fuel-count",
    order = "ba",
    setting_type = "startup",
    default_value = 44,
  },
  {
	type = "bool-setting",
	name = "Monowheel",
	order = "ca",
	setting_type = "startup",
	default_value = true,
  },
  {
    type = "int-setting",
    name = "Wheel-fuel-count",
    order = "cb",
    setting_type = "startup",
    default_value = 11,
  },
  {
	type = "string-setting",
	name = "Wheel-fuel-type",
	order = "cc",
	setting_type = "startup",
	default_value = "nuclear-fuel",
	allowed_values = {"nuclear-fuel","rocket-fuel"},
  },
  {
	type = "string-setting",
	name = "Battery-type",
	order = "dab",
	setting_type = "startup",
	default_value = "big-battery-mk3-equipment",
	allowed_values = {"battery-equipment","big-battery-equipment","battery-mk2-equipment","big-battery-mk2-equipment","battery-mk3-equipment","big-battery-mk3-equipment"},
  },
  {
	type = "int-setting",
	name = "Battery-count",
	order = "dac",
	setting_type = "startup",
	default_value = 5,
  },
  {
	type = "string-setting",
	name = "Reactor-type",
	order = "dba",
	setting_type = "startup",
	default_value = "antimatter-reactor-equipment",
	allowed_values = {"small-portable-generator","portable-generator","nuclear-reactor-equipment","fusion-reactor-equipment","antimatter-reactor-equipment"},
  },
  {
	type = "int-setting",
	name = "Reactor-count",
	order = "dbb",
	setting_type = "startup",
	default_value = 6,
  },
  {
	type = "string-setting",
	name = "Reactor-fuel-type",
	order = "dbc",
	setting_type = "startup",
	default_value = "charged-antimatter-fuel-cell",
	allowed_values = {"dt-fuel", "charged-antimatter-fuel-cell"}
  },
  {
	type = "int-setting",
	name = "Reactor-fuel-count",
	order = "dbd",
	setting_type = "startup",
	default_value = 66,
  },
  {
	type = "string-setting",
	name = "Exoskel-type",
	order = "dca",
	setting_type = "startup",
	default_value = "superior-exoskeleton-equipment",
	allowed_values = {"exoskeleton-equipment","advanced-exoskeleton-equipment","superior-exoskeleton-equipment"},
  },
  {
	type = "int-setting",
	name = "Exoskel-count",
	order = "dcb",
	setting_type = "startup",
	default_value = 1,
  },
  {
	type = "string-setting",
	name = "Vision-type",
	order = "dda",
	setting_type = "startup",
	default_value = "imersite-night-vision-equipment",
	allowed_values = {"night-vision-equipment","imersite-night-vision-equipment"},
  },
  {
	type = "string-setting",
	name = "Panel-type",
	order = "dea",
	setting_type = "startup",
	default_value = "imersite-solar-panel-equipment",
	allowed_values = {"solar-panel-equipment","big-solar-panel-equipment","imersite-solar-panel-equipment","big-imersite-solar-panel-equipment"},
  },
  {
	type = "int-setting",
	name = "Panel-count",
	order = "deb",
	setting_type = "startup",
	default_value = 2,
  },
  {
	type = "string-setting",
	name = "Armor-type",
	order = "dfa",
	setting_type = "startup",
	default_value = "power-armor-mk4",
	allowed_values = {"modular-armor","power-armor","power-armor-mk2","power-armor-mk3","power-armor-mk4"},
  }
})